name: Build and Test

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.202
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore

  test:
    name: "Test"
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: install_mst
        run: |
          curl -L https://cdn.ballstreettrading.com/linux-x64/mst -o mst
          chmod +x ./mst
          ./mst debug
      - name: install_mongodb
        run: ./mst install mongod -v 4.4.13
      - name: launch_replica_set
        run: ./mst launch replica 4.4.13 -p 28017 -d bsttest --fork
      - name: test_replica_set
        run: ps auxf | grep mongod
      - name: Test
        run: dotnet test --no-build --verbosity normal
